### ISSUE TITLE
Implement feature scaling

### ISSUE THREAD

**Issue by TheExecuter1** [dsc-gtbit/HacktoberFest-20-GTBIT-ML#15]
#9  Features x_1 and x_2 are of different scales , use Standard Scaler  from Sklearn to scale the features to similar size , thus boosting the performance of model .
Link to notebook -
https://github.com/dsc-gtbit/HacktoberFest-20-GTBIT-ML/blob/master/Intermediate/Binary%20Classification%20with%20Logistic%20regression/Classification.ipynb

**Comment by Mridul20** [comment]
Can I work on this issue?

**Comment by midopooler** [comment]
Sure @Mridul20 , Go ahead!
